# Generated by Django 4.1.1 on 2022-10-02 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessee',
            fields=[
                ('odiuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('authentication_service', models.CharField(choices=[('default', 'default'), ('google', 'google')], default=users.models.AuthenticationService['DEFAULT'], max_length=120)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.odiuser',),
        ),
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('odiuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('employee_id', models.CharField(max_length=50, null=True)),
                ('authentication_service', models.CharField(choices=[(users.models.AuthenticationService['DEFAULT'], 'default'), (users.models.AuthenticationService['GOOGLE'], 'google')], default=users.models.AuthenticationService['DEFAULT'], max_length=120)),
                ('associated_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.odiuser',),
        ),
    ]
