# Generated by Django 4.1.1 on 2022-10-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_assessee_assessor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='authentication_service',
            field=models.CharField(choices=[('default', 'default'), ('google', 'google')], default='default', max_length=120),
        ),
    ]
