# Generated by Django 4.1.1 on 2022-10-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_assessor_authentication_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessee",
            name="authentication_service",
            field=models.CharField(
                choices=[("default", "default"), ("google", "google")],
                default="default",
                max_length=120,
            ),
        ),
    ]
