# Generated by Django 4.1.1 on 2022-10-23 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssessmentTool",
            fields=[
                (
                    "assessment_id",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(null=True)),
                (
                    "owning_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("points", models.IntegerField(default=0)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Question"),
                            ("multiple_choice", "Multiple Choice Question"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "assessmenttool_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assessment.assessmenttool",
                    ),
                ),
                ("expected_file_format", models.CharField(max_length=5, null=True)),
                ("duration_in_minutes", models.IntegerField()),
            ],
            bases=("assessment.assessmenttool",),
        ),
        migrations.CreateModel(
            name="InteractiveQuiz",
            fields=[
                (
                    "assessmenttool_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assessment.assessmenttool",
                    ),
                ),
                ("duration_in_minutes", models.IntegerField()),
                ("total_points", models.IntegerField()),
            ],
            bases=("assessment.assessmenttool",),
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assessment.question",
                    ),
                ),
            ],
            bases=("assessment.question",),
        ),
        migrations.CreateModel(
            name="TextQuestion",
            fields=[
                (
                    "question_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assessment.question",
                    ),
                ),
                ("answer_key", models.TextField(null=True)),
            ],
            bases=("assessment.question",),
        ),
        migrations.AddField(
            model_name="question",
            name="interactive_quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessment.interactivequiz",
            ),
        ),
        migrations.CreateModel(
            name="MultipleChoiceAnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessment.multiplechoicequestion",
                    ),
                ),
            ],
        ),
    ]
