# Generated by Django 4.1.1 on 2022-12-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="questionattempt", old_name="note", new_name="question_note",
        ),
    ]
