# Generated by Django 4.1.1 on 2022-11-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsetest", name="sender", field=models.TextField(),
        ),
    ]
