# Generated by Django 4.1.1 on 2022-10-09 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmenttool",
            name="owning_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.company"
            ),
        ),
    ]
