# Generated by Django 4.1.1 on 2022-12-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionattempt",
            name="interactive_quiz_attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessment.interactivequizattempt",
            ),
        ),
    ]
