# Generated by Django 4.1.1 on 2022-10-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessment", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmenttool",
            name="owning_company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.company"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="interactive_quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessment.interactivequiz",
            ),
        ),
        migrations.AddField(
            model_name="multiplechoiceansweroption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessment.multiplechoicequestion",
            ),
        ),
    ]
