# Generated by Django 4.1.1 on 2022-12-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_multiplechoiceansweroptionattempt_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoiceansweroptionattempt',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
