# Generated by Django 4.1.1 on 2022-10-25 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmenttool',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='assessmenttool',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
