# Generated by Django 4.1.1 on 2022-12-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_interactivequizattempt_submitted_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolattempt',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
