# Generated by Django 4.1.1 on 2022-12-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_alter_responsetest_sender"),
        ("assessment", "0003_toolattempt_note"),
    ]

    operations = []
