# Generated by Django 4.1.1 on 2022-12-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_multiplechoiceansweroptionattempt_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='textquestionattempt',
            name='awarded_points',
            field=models.FloatField(default=0),
        ),
    ]
