# Generated by Django 4.1.1 on 2022-10-27 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_testflow_testflowtool_testflow_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='testflowtool',
            name='start_working_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
