# Generated by Django 4.1.1 on 2022-12-06 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_merge_20221205_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTestAttempt',
            fields=[
                ('toolattempt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessment.toolattempt')),
                ('submitted_time', models.DateTimeField(default=None, null=True)),
                ('subject', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('assessment.toolattempt',),
        ),
    ]
