# Generated by Django 4.1.1 on 2022-10-28 04:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('assessment', '0005_testflowtool_start_working_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(auto_created=True, default=uuid.uuid4)),
                ('name', models.CharField(max_length=50)),
                ('start_date_time', models.DateTimeField()),
                ('owning_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('test_flow_used', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='assessment.testflow')),
            ],
        ),
    ]
