# Generated by Django 4.1.1 on 2022-12-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0005_videoconferencenotification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoconferencenotification", name="time_release",
        ),
    ]
