# Generated by Django 4.1.1 on 2022-12-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0005_responsetestattempt"),
        ("assessment", "0006_remove_videoconferencenotification_time_release"),
    ]

    operations = []
