# Generated by Django 4.1.1 on 2022-10-28 09:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('assessment', '0006_assessmentevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentEventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.assessee')),
                ('assessment_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentevent')),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.assessor')),
            ],
        ),
        migrations.CreateModel(
            name='TestFlowAttempt',
            fields=[
                ('attempt_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('note', models.TextField(null=True)),
                ('grade', models.FloatField(default=0)),
                ('event_participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmenteventparticipation')),
                ('test_flow_attempted', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='assessment.testflow')),
            ],
        ),
        migrations.AddField(
            model_name='assessmenteventparticipation',
            name='attempt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.testflowattempt'),
        ),
    ]
