# Generated by Django 4.1.1 on 2022-10-28 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("assessment", "0007_assessmenteventparticipation_testflowattempt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseTest",
            fields=[
                (
                    "assessmenttool_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assessment.assessmenttool",
                    ),
                ),
                ("subject", models.TextField()),
                ("prompt", models.TextField()),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.assessor"
                    ),
                ),
            ],
            options={"abstract": False, "base_manager_name": "objects",},
            bases=("assessment.assessmenttool",),
        ),
    ]
