# Generated by Django 4.1.1 on 2022-10-30 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('assessment', '0007_assessmenteventparticipation_testflowattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConferenceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.TextField(default=None, null=True)),
                ('room_opened', models.BooleanField(default=False)),
                ('conference_participants', models.ManyToManyField(to='users.assessor')),
                ('part_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmenteventparticipation')),
            ],
        ),
    ]
