# Generated by Django 4.1.1 on 2022-11-01 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0008_responsetest"),
        ("assessment", "0008_videoconferenceroom"),
    ]

    operations = []
