# Generated by Django 4.1.1 on 2022-11-05 04:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('assessment', '0009_merge_0008_responsetest_0008_videoconferenceroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolAttempt',
            fields=[
                ('tool_attempt_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('grade', models.FloatField(default=0)),
                ('assessment_tool_attempted', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmenttool')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('test_flow_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.testflowattempt')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AlterModelOptions(
            name='interactivequiz',
            options={'base_manager_name': 'objects'},
        ),
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('toolattempt_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assessment.toolattempt')),
                ('file_upload_directory', models.TextField(null=True)),
                ('filename', models.TextField(default=None, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('assessment.toolattempt',),
        ),
    ]
