# Generated by Django 4.1.1 on 2022-11-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_toolattempt_alter_interactivequiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentattempt',
            name='submitted_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
