# Generated by Django 4.1.1 on 2022-11-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_assignmentattempt_submitted_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testflowtool',
            options={'get_latest_by': 'start_working_time', 'ordering': ['release_time', 'start_working_time']},
        ),
    ]
