# Generated by Django 4.1.1 on 2022-10-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_conference', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoConferenceRoom',
        ),
    ]
