name: Staging
on:
  push:
    branches:
      - 'staging'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.10
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Collect Static Files
        run: python manage.py collectstatic --no-input
      - name: Run Test
        run: python manage.py test
        env:
          DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}

  staging:
    needs: test
    if: github.ref == 'refs/heads/staging'
    name: Staging to Cloud Run
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.STAGING_GCP_PROJECT_ID }}/${{ secrets.STAGING_GCP_APP_NAME }}
    steps:
      - name: Staging Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.STAGING_GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.STAGING_GCP_EMAIL }}
          service_account_key: ${{ secrets.STAGING_GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME --build-arg arg_database_url=${{ secrets.STAGING_DATABASE_URL }} .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        run: gcloud run deploy ${{ secrets.STAGING_GCP_PROJECT_ID }} --image $IMAGE_NAME --region us-central1 --platform managed
